/*
 * Note: 
 * Do not edit this file directly!  Please copy it to your config.js and setup the values correctly.
 */

var config = {
    TRELLO_WEBHOOK_URL: 'http://www.example.com:3030/trello_callback',
    PORT: 3000,
    TRELLO_API_KEY: '7f4f77uuuuuuuuuuu1b7c483176b13c6',
    TRELLO_API_TOKEN: '3dac5b4014uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuf6bd4c271a4',
    TRELLO_CLIENT_SECRET: '8868uuuuuuuuuuuuuuuuuuuuuudc2c03675dfaca353d42ed26f8573f78580b5f',
    MODELID_SUBSCRIPTIONS: { },
    TRELLOID_MAP_DINGTALKID: {}
};
process.AppConfig = config;
var subscriptions = config.MODELID_SUBSCRIPTIONS;


// maping trello user id to dingtalk user id(mobile number)
config.TRELLOID_MAP_DINGTALKID = {
    'nuuuuaster': "13000000821",
    'iuuuuuct1': "13300000022", 
    'luuuuchun': "18900000060",
    'muuuu': "18910000003",
    "zuuuucyf1": '15000000641',
    'zuuuum1': '18910000004',
    'zuuuuyfk': "18600000012",
    'suuuu0092871':  "15000000018",
    'kuuuug1': "18000000719", 
    'luuuuliang9': "18600000090" 
}


// Trello ITWORK Board --> Dingding Project Group (or others)
var DDGroup_Token_PROJECT = '69e658uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu3f9a79c8ef6e80b342';
var TRELLO_BOARDID_ITWORK = '59uuuuuuuuuuuuuuuuuuuuuu';
subscriptions[TRELLO_BOARDID_ITWORK] = [DDGroup_Token_PROJECT];

// Trello Test Board --> Dingding Test Group (or others)
var DDGroup_Token_TEST = '94277cuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu';
var TRELLO_BOARDID_TEST = '59ba2uuuuuuuuuuuuuuuuuuu';
subscriptions[TRELLO_BOARDID_TEST] = [DDGroup_Token_TEST]; 

// Trello OPS Board --> Dingding Board Group(or others)
var TRELLO_BOARDID_OPS = '59f170uuuuuuuuuuuuuuuuuu'; 
var DDGroup_Token_OPS = '6f32df8uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu';
subscriptions[TRELLO_BOARDID_OPS] = [DDGroup_Token_OPS]; 

